version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - db-volume:/docker-entrypoint-initdb.d/
      - db-volume:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=owl_forest
    ports:
      - 3306:3306
    expose:
      - 3306
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379

volumes:
  db-volume:
