apiVersion: apps/v1
kind: Deployment
metadata:
  name: owl-forest-backend
spec:
  selector:
    matchLabels:
      app: owl-forest-backend
      component: owl-forest-backend
      tier: back
  replicas: 1
  template:
    metadata:
      labels:
        app: owl-forest-backend
        component: owl-forest-backend
        tier: back
    spec:
      containers:
        - name: owl-forest-backend
          image: phjppo0918/owlforest-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.port
            - name: DATABASE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.schema
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database.password