apiVersion: v1
kind: Service
metadata:
  name: owlforest-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: owlforest-backend
    component: owlforest-backend
    tier: back