apiVersion: apps/v1
kind: Deployment
metadata:
  name: owlforest-redis
spec:
  selector:
    matchLabels:
      app: owlforest-redis
      component: owlforest-redis
      tier: back
  replicas: 1
  template:
    metadata:
      labels:
        app: owlforest-redis
        component: owlforest-redis
        tier: back
    spec:
      containers:
        - name: owlforest-redis
          image: redis:latest
          ports:
            - containerPort: 6379