apiVersion: v1
kind: Service
metadata:
  name: owlforest-mysql-master
spec:
  ports:
    - name: owlforest-mysql-master
      port: 3307
      targetPort: 3306
      protocol: TCP
  selector:
    app: owlforest-mysql-master
    component: owlforest-mysql-master
  clusterIP: None
