apiVersion: v1
kind: Service
metadata:
  name: owlforest-redis
spec:
  ports:
    - name: owlforest-redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: owlforest-redis
    component: owlforest-redis
  clusterIP: None
