apiVersion: v1
kind: Service
metadata:
  name: owlforest-mysql
spec:
  ports:
    - name: owlforest-mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: owlforest-mysql
    component: owlforest-mysql
  clusterIP: None
