apiVersion: apps/v1
kind: Deployment
metadata:
  name: owl-forest-frontend
  labels:
    app: owl-forest-frontend
    tier: front
spec:
  selector:
    matchLabels:
      app: owl-forest-frontend
      tier: front
  replicas: 1
  template:
    metadata:
      labels:
        app: owl-forest-frontend
        tier: front
    spec:
      containers:
        - name: owlforest-frontend
          image: phjppo0918/owlforest-frontend:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: server.url
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: server.port
          ports:
            - containerPort: 80
