apiVersion: v1
kind: Service
metadata:
  name: owlforest-frontend
spec:
  type: NodePort
  selector:
    app: owlforest-frontend
    tier: front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31313
