apiVersion: v1
kind: Service
metadata:
  name: owl-forest-frontend
spec:
  type: NodePort
  selector:
    app: owl-forest-frontend
    tier: front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30003
