apiVersion: v1
kind: Service
metadata:
  name: owlforest-mysql-slave-dev
spec:
  ports:
    - name: owlforest-mysql-slave-dev
      port: 3307
      targetPort: 3306
      protocol: TCP
  selector:
    app: owlforest-mysql-slave-dev
    component: owlforest-mysql-slave-dev
  clusterIP: None
