apiVersion: v1
kind: Service
metadata:
  name: owlforest-mysql-slave
spec:
  ports:
    - name: owlforest-mysql-slave
      port: 3307
      targetPort: 3306
      protocol: TCP
  selector:
    app: owlforest-mysql-slave
    component: owlforest-mysql-slave
  clusterIP: None
