logging:
  level:
    org:
      springframework: debug
      web: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tbl_reply?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Tngus0807^^
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

