name: OWL-FOREST Github Actions
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test

  replace-google-format:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: '--replace'
          github-token: ${{ secrets.GITHUB_TOKEN }}
