name: OWL-FOREST Github Actions
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd backend
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
  
  replace-google-format:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - run: cd backend
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
