name: OWL-FOREST Github Actions
on: [push, pull_request]
defaults:
  run:
    shell: bash
    working-directory: ./backend
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - run: gradle test

  replace-google-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: '--replace --aosp'
          github-token: ${{ secrets.GITHUB_TOKEN }}
