name: OWL-FOREST Github Actions
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - run: chmod +x gradlew
      - run: ./gradlew test

  replace-google-format:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: '--replace'
          github-token: ${{ secrets.GITHUB_TOKEN }}
